packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: ^19.2.0
  react-dom: ^19.1.0
  eslint: ^9.38.0
  postcss: ^8.5.3
  tailwindcss: ^4
  typescript: 5.9.2
  next: 15.5.7
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.1
  '@tailwindcss/postcss': ^4
